services:
  PrestaShop\Module\NeftysFarmaConnector\Command\ForceUpdateOrderCommand:
    tags:
      - {name: 'console.command'}
  PrestaShop\Module\NeftysFarmaConnector\Command\TestFtpCommand:
    tags:
      - { name: 'console.command' }