CREATE TABLE IF NOT EXISTS `PREFIX_kpymenu_categories` (
	`id_category` INT UNSIGNED NOT NULL,
	`position` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id_category`)
) ENGINE = ENGINE_TYPE DEFAULT CHARSET = utf8;