<?php

namespace PrestaShop\Module\KpyProductForm\Entity;

use ObjectModel;

class KpyCombination extends ObjectModel
{
    public int $id_product_attribute;

    public bool $active = true;

    /**
     * @var bool forces the id to be set before saving object (because we don't need autogenerated id for this model)
     */
    public $force_id = true;

    public static $definition = [
        'table' => 'kpy_product_attribute',
        'primary' => 'id_product_attribute',
        'fields' => [
            'active' => ['type' => self::TYPE_BOOL],
        ],
    ];
}